version: '3'
services:
  web:
    image: nginx:1.16.1
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/src:/var/www/
      - ./web/logs:/var/log/nginx/
    depends_on:
      - php1
      - php2

  php1:
    image: php:7.4.3-fpm
    container_name: php1
    ports:
      - 9000:9000
    volumes:
      - ./php/php/src:/var/www/html
      - ./php/php/conf/www1.conf:/usr/local/etc/php-fpm.d/www.conf

  php2:
    image: php:7.4.3-fpm
    container_name: php2
    ports:
      - 9001:9000
    volumes:
      - ./php/php/src:/var/www/html
      - ./php/php/conf/www2.conf:/usr/local/etc/php-fpm.d/www.conf